"""empty message

Revision ID: 35a0b1b766b1
Revises: 1bfab4341712
Create Date: 2025-08-28 18:31:40.650945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a0b1b766b1'
down_revision = '1bfab4341712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_required', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('certificate_required')

    # ### end Alembic commands ###
