"""empty message

Revision ID: 685458a7c3e8
Revises: 
Create Date: 2025-08-03 14:50:22.320008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685458a7c3e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_organisation', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('company_organisation')

    # ### end Alembic commands ###
