"""empty message

Revision ID: 95751c560ba7
Revises: 97b362d56c06
Create Date: 2025-08-10 11:45:49.028848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95751c560ba7'
down_revision = '97b362d56c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
