"""empty message

Revision ID: 97b362d56c06
Revises: dde1d6ddd78d
Create Date: 2025-08-04 23:14:43.769752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b362d56c06'
down_revision = 'dde1d6ddd78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_inquiry', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('other_inquiry')

    # ### end Alembic commands ###
