"""empty message

Revision ID: dde1d6ddd78d
Revises: df27b3dc6472
Create Date: 2025-08-03 18:05:17.222080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde1d6ddd78d'
down_revision = 'df27b3dc6472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disapproval_reason', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('company_organisation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('age_group',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('highest_qualification',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('registration_category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('hotel_lodging',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('travel_visa',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('travel_visa',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('hotel_lodging',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('registration_category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('highest_qualification',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('age_group',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('company_organisation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('disapproval_reason')

    # ### end Alembic commands ###
